name: Java Code Linters

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  call-reusable-linting:
    # In a real-world scenario, this would be:
    # uses: this-is-my-org-2/.github/.github/workflows/java-linting-reusable.yml@main
    uses: ./.github/workflows/java-linting-reusable.yml
    with:
      checkstyle-config: 'config/checkstyle/checkstyle.xml'
      checkstyle-pattern: 'build/reports/checkstyle/*.xml'
      pmd-rulesets: 'rulesets/java/quickstart.xml'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}